alimentos/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', alimentos, name="alimentos"),
]

celita/urls.py
from django.contrib import admin
from django.urls import path,include
from core.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",portada, name="portada"),
    path("calculadora",calculadora, name="calculadora"),
    path('alimentos',include ('alimentos.urls')),
    path('recetas',include ('recetas.urls')),
    path('ingredientes',include ('ingredientes.urls')),
    path('comidas',include ('comidas.urls')),
    path('platos',include ('platos.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alimentos/models.py
from django.db import models

# Create your models here.
class Alimentos(models.Model):
    CAT_CHOICES=(("1","verduras"),("2","frutas"),("3","farináceos"),("4","lácteos"),("5","grasas"))
    nombre=models.CharField(max_length=100)
    categoria=models.CharField(max_length=5, choices=CAT_CHOICES, default='1')
    racion=models.DecimalField(max_digits=6, decimal_places=2)


    def __str__(self):
            return self.nombre
    
    class Meta():
        ordering=['nombre']

alimentos/views.py
from django.shortcuts import render
from .models import Alimentos


# Create your views here.

def alimentos(request):
    alimentos=Alimentos.objects.all()
    return render(request,"alimentos/alimentos.html",{"alimentos":alimentos})

templates/alimentos/alimentos.html
{%extends "base.html"%}
{%load static%}
{%block contenido%}
<div class="alimentos container text-center">
<img src="{%static 'images/alimentos.jpg'%}"></img>
</div>
<br>
<div class="tabla-alimentos container text-center">
    <table id="tabla_alimentos" class="display">
        <thead>
        <tr>
            <th> Cantidad por ración</th>
            <th> Nombre</th>
            <th> Categoria</th>
        </tr>
        </thead>
        <tbody>
        {%for alimento in alimentos%}
        <tr>
            <td>{{alimento.racion}}</td>
            <td>{{alimento.nombre}}</td>
            <td>{{alimento.get_categoria_display}}</td>
        </tr>
        {%endfor%}
    </tbody>
    </table>
    <br>
    </div>
    
{%endblock%}